spring:
  datasource:
    url: jdbc:mysql://localhost:3306/constatv2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: fsjsbouheli@gmail.com
    password: psppgyfioyaclelv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
      test-connection: false
  jackson:
    serialization:
      fail-on-empty-beans: false
application:
  security:
    jwt:
      secret-key: 2646294A404E635266556A586E5A7234753778214125442A472D4B6150645367
      expiration: 86400000 #60000#
      refresh-token:
        expiration: 604800000 # 7 days

servlet:
  multipart:
    max-file-size: 2MB
    max-request-size: 2MB




  # This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
